"""Private, content-addressed object storage. SDK imports stay inside the server factory."""
from contextlib import asynccontextmanager
from dataclasses import dataclass
import hashlib
import re
from typing import Protocol


@dataclass(frozen=True)
class ObjectInfo:
    content_hash: str
    size: int


R2_ENDPOINT_RE = re.compile(r"https://[0-9a-f]{32}(?:\.(?:eu|fedramp))?\.r2\.cloudflarestorage\.com")


class ObjectStore(Protocol):
    async def put(self, body: bytes, *, content_hash: str | None = None) -> ObjectInfo: ...
    async def get(self, content_hash: str) -> bytes | None: ...
    async def head(self, content_hash: str) -> ObjectInfo | None: ...
    async def delete(self, content_hash: str) -> None: ...


class NamedObjectStore(Protocol):
    """Objects a caller finds by a name it derives, not by their content (find's card vectors)."""
    async def put_named(self, name: str, body: bytes) -> None: ...
    async def get_named(self, name: str) -> bytes | None: ...


# A named object: `<namespace>/<slug>/<sha256 hex>`, built by treg from a slug and a digest, never
# from a request (find's card vectors: `find-vectors/<model>/<card hash>`).
NAMED_RE = re.compile(r"[a-z][a-z0-9-]{0,63}/[a-z0-9][a-z0-9._-]{0,127}/[0-9a-f]{64}")


def _named_key(name: str) -> str:
    if not NAMED_RE.fullmatch(name):
        raise ValueError("invalid object name")
    return name


def _key(content_hash: str) -> str:
    # Only hashes generated by treg or read from its archive are accepted, never a path or URL.
    if not re.fullmatch(r"[0-9a-f]{64}", content_hash):
        raise ValueError("invalid archive content hash")
    return content_hash


class ObjectStoreError(ValueError):
    """A bounded, credential-free reason at the SDK boundary."""
    def __init__(self, reason: str, *, exception_type: str | None = None):
        self.reason = reason
        self.exception_type = exception_type
        super().__init__(reason)


_FAILURE_REASONS = frozenset({"not_found", "timeout", "permission_denied", "hash_mismatch",
                              "too_large", "store_unavailable", "store_error", "rate_limited",
                              "upstream_error"})
# obstore 0.11 GenericError has no status attribute. Match only its transport prefix, never a
# bare number or provider response body. The SDK exception text must not leave this boundary.
_HTTP_STATUS = re.compile(
    r"^Generic S3 error: Error performing (?:PUT|GET|HEAD) \S+ in [^\r\n]+?"
    r" - Server returned non-2xx status code: ([0-9]{3})\b")


def failure_reason(exc: Exception) -> str:
    if isinstance(exc, ObjectStoreError):
        return exc.reason if exc.reason in _FAILURE_REASONS else "store_error"
    if isinstance(exc, PermissionError):
        return "permission_denied"
    if isinstance(exc, FileNotFoundError):
        return "not_found"
    if isinstance(exc, TimeoutError):
        return "timeout"
    return "store_error"


def exception_name(exc: Exception) -> str:
    return (getattr(exc, "exception_type", None) or type(exc).__name__)[:80]


class R2ObjectStore:
    def __init__(self, client, max_body_bytes: int, *, auth_errors=(), status_errors=()):
        self._client, self._max_bytes = client, max_body_bytes
        self._auth_errors = (PermissionError, *auth_errors)
        self._status_errors = status_errors

    async def put(self, body: bytes, *, content_hash: str | None = None) -> ObjectInfo:
        key = _key(content_hash) if content_hash is not None else hashlib.sha256(body).hexdigest()
        await self._put(key, body)
        return ObjectInfo(key, len(body))

    async def _put(self, key: str, body: bytes) -> None:
        if len(body) > self._max_bytes:
            raise ValueError("object body too large")
        try:
            await self._client.put_async(
                key, body, attributes={"Content-Type": "application/octet-stream"}, use_multipart=False)
        except Exception as exc:
            raise self._failure(exc) from None

    async def _get(self, key: str) -> bytes | None:
        try:
            result = await self._client.get_async(key)
            if result.meta["size"] > self._max_bytes:
                raise ObjectStoreError("too_large")
            body = bytes(await result.bytes_async())
            if len(body) > self._max_bytes:
                raise ObjectStoreError("too_large")
            return body
        except FileNotFoundError:
            return None
        except ObjectStoreError:
            raise
        except Exception as exc:
            raise self._failure(exc) from None

    async def head(self, content_hash: str) -> ObjectInfo | None:
        key = _key(content_hash)
        try:
            meta = await self._client.head_async(key)
        except FileNotFoundError:
            return None
        except Exception as exc:
            raise self._failure(exc) from None
        return ObjectInfo(key, int(meta["size"]))

    async def get(self, content_hash: str) -> bytes | None:
        key = _key(content_hash)
        body = await self._get(key)
        if body is not None and hashlib.sha256(body).hexdigest() != key:
            raise ObjectStoreError("hash_mismatch")
        return body

    async def delete(self, content_hash: str) -> None:
        """Remove one archive body. The only delete the store offers, used by the erasure sweep
        alone (application/archive_erasure.py): a content-addressed object may carry bytes for
        several snapshots, so the caller proves no row still points at it before calling.
        A missing object is already deleted, not an error."""
        key = _key(content_hash)
        try:
            await self._client.delete_async(key)
        except FileNotFoundError:
            return
        except Exception as exc:
            raise self._failure(exc) from None

    async def put_named(self, name: str, body: bytes) -> None:
        """A named object has no content address to verify on read: its body must carry its own
        integrity check (find_index's header)."""
        await self._put(_named_key(name), body)

    async def get_named(self, name: str) -> bytes | None:
        return await self._get(_named_key(name))

    def _failure(self, exc):
        reason = failure_reason(exc)
        if isinstance(exc, self._auth_errors):
            reason = "permission_denied"
        elif isinstance(exc, self._status_errors):
            match = _HTTP_STATUS.match(str(exc))
            if match:
                status = int(match[1])
                if status == 429:
                    reason = "rate_limited"
                elif 500 <= status < 600:
                    reason = "upstream_error"
        return ObjectStoreError(reason, exception_type=type(exc).__name__)


@asynccontextmanager
async def open_r2(settings):
    from obstore.exceptions import GenericError, PermissionDeniedError, UnauthenticatedError
    from obstore.store import S3Store

    transport_timeout = max(settings.archive_r2_timeout_s, settings.archive_r2_read_timeout_s)
    client = S3Store(
        settings.archive_object_store_bucket,
        config={
            "endpoint": settings.archive_object_store_endpoint, "region": "auto",
            "access_key_id": settings.archive_object_store_access_key_id,
            "secret_access_key": settings.archive_object_store_secret_access_key,
            "checksum_algorithm": "SHA256",
        },
        client_options={"timeout": f"{transport_timeout}s",
                        "connect_timeout": f"{transport_timeout}s"},
        retry_config={"max_retries": 0})
    # One shared Rust HTTP pool for the lifespan. S3Store has no explicit close operation;
    # dropping the store after archive drains releases its client and pool.
    yield R2ObjectStore(client, settings.archive_max_body_bytes,
                        auth_errors=(PermissionDeniedError, UnauthenticatedError), status_errors=(GenericError,))
